# Generated by Django 2.1.5 on 2019-02-25 04:40

import datetime
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20170227_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondescription',
            name='link_subtype',
            field=models.CharField(choices=[('beginning', 'Beginning'), ('end', 'End')], max_length=64),
        ),
        migrations.AlterField(
            model_name='commondescription',
            name='link_type',
            field=models.CharField(choices=[('room', 'Room'), ('talk', 'Talk')], max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='backup_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='broadcast_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='cdn_format',
            field=models.CharField(choices=[('1080p', '1080p'), ('1080p_hfr', '1080p_hfr'), ('720p', '720p'), ('720_hfr', '720p_hfr'), ('480p', '480p'), ('360p', '360p'), ('240p', '240p')], default='1080p', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='ingestion_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='room',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=django_fsm.FSMField(default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='stream_name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='room',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='talk',
            name='broadcast_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='talk',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 20, 40, 29, 133482), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='state',
            field=django_fsm.FSMField(default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
