# Generated by Django 2.1.5 on 2019-03-04 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20190224_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_dual_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='save_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 3, 20, 34, 7, 95726), verbose_name='date published'),
        ),
    ]
