# Generated by Django 2.1.5 on 2019-03-04 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20190303_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 4, 0, 42, 43, 725822), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
