# Generated by Django 2.1.5 on 2020-03-03 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20190304_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='recordable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='streamable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 2, 18, 41, 50, 732862), verbose_name='date published'),
        ),
    ]
