#!/usr/bin/env python

import sys, os
from daemon import Daemon
from utils.background import YtScheduleBG

rundir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../run'))
class LocalBackground(YtScheduleBG):
  def work(self):
    print "here!"
if __name__ == "__main__":
  daemon = LocalBackground( os.path.join(rundir, "%s.pid" % os.path.basename(__file__)) )
  daemon.process_cmd(sys.argv)

