#!/bin/bash
#first pass a a pipeline to push from SNP-6200 rtsp to gst-switch.

#this test pipe line should provide data from snp-6200 to gst-switch
ipaddress=$1

gst-launch-1.0 -v -m rtspsrc location=rtsp://${ipaddress}/1 latency=0 ntp-sync=true is-live=true do-timestamp=true name=camera \
  camera. ! "application/x-rtp,media=video,payload=96" ! rtph264depay ! queue ! \
  vaapiparse_h264 ! decodebin ! typefind name=finder ! \
   video/x-raw, format=I420, pixel-aspect-ratio=1/1, interlace-mode=progressive ! \
  queue ! fpsdisplaysink sync=false \
  camera. ! rtpmp4gdepay ! queue ! audio/mpeg, mpegversion=4, stream-format=raw ! aacparse ! typefind ! faad ! queue ! autoaudiosink silent=0 
exit
